#---------------------------------------------------------------------
# Helm template for k8s to deploy simple web app
#
# Created by Vlad Patoka, who is looking for a job
#---------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployemnt-autoscaling-app
  labels:
    app: {{ .Release.Name }}-deployemnt-app
    owner: VladPatoka
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-app-container
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.port }}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-autoscaling-app
  labels:
    app: {{ .Release.Name }}-deployemnt-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ .Release.Name }}-deployment-autoscaling
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.cpuThreshold }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.memThreshold }}

