# Service for Application
#
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  labels:
    app: {{ .Release.Name }}
    env: poc
    owner: VladPatoka
spec:
  selector:
    app: {{ .Release.Name }} # Selecting pods with those labels
  ports:
    - name: {{ .Release.Name }}-app-listener
      protocol: TCP
      port: {{ .Values.app_port }}
      targetPort: {{ .Values.trg_port }}
  type: LoadBalancer

# Service for ArgoCD
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: argocd-server
#  namespace: argocd
#  labels:
#    {{ .Release.Name }}.kubernetes.io/name: argocd-server
#    {{ .Release.Name }}.kubernetes.io/part-of: argocd
#spec:
#  selector:
#    {{ .Release.Name }}.kubernetes.io/name: argocd-server
#  ports:
#    - name: http
#      port: 80
#      targetPort: {{ .Values.argo_port }}
#
#    - name: https
#      port: 443
#      targetPort: {{ .Values.https_argo_port }}
#
#  type: LoadBalancer
