#---------------------------------------------------------------------
# GIT action for CI part to create artifact (container) and push it to
# Google Cloud Container Storage
#
# Created by Vlad Patoka, who is looking for a job
#---------------------------------------------------------------------
name: Deploy Web Server

on:
  push:
    branches:
      - main

env:
  PROJECT: PoC
  IMAGE_NAME: my_web_app
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        version: '>= 363.0.0'

    - name: Authenticate Docker to Google Cloud
      run:
        gcloud auth configure-docker

    - name: Build Docker image
      run:
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest .

    - name: Auth access to Docker repo
      run:
        gcloud auth configure-docker --quiet # authenticate to GCR

    - name: Push Docker image to Google Container Registry
      run: |-
        docker tag ${{ env.IMAGE_NAME }}:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest 
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
